defmodule Mix.Tasks.SpectreKinetic.DownloadEncoder do
  use Mix.Task

  @moduledoc """
  Downloads and exports a Hugging Face encoder model to ONNX format.

  This task downloads the model files needed for the Elixir-native planner:
  `model.onnx`, `tokenizer.json`, and `config.json`.

  ## Usage

      mix spectre_kinetic.download_encoder \\
        --model BAAI/bge-small-en-v1.5 \\
        --revision 5c38ec7c405ec4b44b94cc5a9bb96e735b38267a \\
        --out artifacts/encoder

  ## Options

    * `--model` — Hugging Face model ID (default `BAAI/bge-small-en-v1.5`)
    * `--revision` — immutable 40-character Hugging Face commit SHA. It may be
      omitted only for the default model, which uses the pin shown above.
    * `--out` — output directory (required)
    * `--force` — overwrite existing files
    * `--checksum-manifest` — optional trusted manifest generated by a previous
      run. Model identity, revision, and every SHA-256 digest must match.

  An exclusive output lock prevents concurrent writers. Downloads are staged
  under the output directory, structurally checked, verified, and atomically
  renamed into place. If a rename fails, already installed files are rolled
  back. A reusable `encoder-manifest.json` is written with the resolved model,
  revision, byte sizes, source URLs, and SHA-256 digests.
  """

  @shortdoc "Download an ONNX encoder model from Hugging Face"

  @default_model "BAAI/bge-small-en-v1.5"
  @default_revision "5c38ec7c405ec4b44b94cc5a9bb96e735b38267a"
  @revision_pattern ~r/\A[0-9a-fA-F]{40}\z/
  @sha256_pattern ~r/\A[0-9a-fA-F]{64}\z/
  @model_segment_pattern ~r/\A[A-Za-z0-9][A-Za-z0-9._-]*\z/
  @files ["model.onnx", "tokenizer.json", "config.json"]
  @manifest_name "encoder-manifest.json"
  @lfs_pointer_prefix "version https://git-lfs.github.com/spec/v1"
  @html_model_prefixes ["<!DOCTYPE html", "<!doctype html", "<html", "<HTML"]

  @switches [
    model: :string,
    revision: :string,
    out: :string,
    force: :boolean,
    checksum_manifest: :string
  ]

  @impl Mix.Task
  def run(argv) do
    opts =
      Keyword.put(options!(argv), :reporter, fn message ->
        Mix.shell().info(message)
      end)

    case download(opts) do
      {:ok, result} ->
        Mix.shell().info("manifest #{result.manifest_path}")
        Mix.shell().info("Encoder model ready at #{result.out_dir}")

      {:error, reason} ->
        Mix.raise(format_error(reason))
    end
  end

  @doc false
  @spec options!([binary()]) :: keyword()
  def options!(argv) when is_list(argv) do
    {opts, args, invalid} = OptionParser.parse(argv, strict: @switches)

    if invalid != [], do: Mix.raise("invalid options: #{inspect(invalid)}")
    if args != [], do: Mix.raise("unexpected arguments: #{inspect(args)}")

    model_id = validate_model_id!(opts[:model] || @default_model)
    revision = revision!(model_id, opts[:revision])
    out_dir = validate_out_dir!(opts[:out])
    checksum_manifest = validate_optional_path!(opts[:checksum_manifest], :checksum_manifest)

    [
      model: model_id,
      revision: revision,
      out: out_dir,
      force: opts[:force] || false,
      checksum_manifest: checksum_manifest
    ]
  end

  @doc false
  @spec hf_url(binary(), binary(), binary()) :: binary()
  def hf_url(model_id, revision, file) do
    model_id = validate_model_id!(model_id)
    revision = validate_revision!(revision)

    # For ONNX files, try the onnx/ subfolder on HF if the model has one
    base = "https://huggingface.co/#{model_id}/resolve/#{revision}"

    case file do
      "model.onnx" -> "#{base}/onnx/model.onnx"
      other when other in ["tokenizer.json", "config.json"] -> "#{base}/#{other}"
      other -> Mix.raise("unsupported encoder file: #{inspect(other)}")
    end
  end

  @spec revision!(binary(), binary() | nil) :: binary()
  defp revision!(@default_model, nil), do: @default_revision

  defp revision!(_model_id, nil) do
    Mix.raise("missing required option --revision for a custom --model")
  end

  defp revision!(_model_id, revision), do: validate_revision!(revision)

  @spec validate_revision!(term()) :: binary()
  defp validate_revision!(revision) when is_binary(revision) do
    if Regex.match?(@revision_pattern, revision) do
      String.downcase(revision)
    else
      invalid_revision!()
    end
  end

  defp validate_revision!(_revision), do: invalid_revision!()

  @spec invalid_revision!() :: no_return()
  defp invalid_revision! do
    Mix.raise("--revision must be an immutable 40-character hexadecimal commit SHA")
  end

  @spec validate_model_id!(term()) :: binary()
  defp validate_model_id!(model_id) when is_binary(model_id) do
    segments = String.split(model_id, "/", trim: false)

    valid? =
      byte_size(model_id) in 1..192 and length(segments) in [1, 2] and
        Enum.all?(segments, &Regex.match?(@model_segment_pattern, &1))

    if valid?, do: model_id, else: invalid_model_id!(model_id)
  end

  defp validate_model_id!(model_id), do: invalid_model_id!(model_id)

  @spec invalid_model_id!(term()) :: no_return()
  defp invalid_model_id!(model_id) do
    Mix.raise("invalid Hugging Face model ID: #{inspect(model_id)}")
  end

  @spec validate_out_dir!(term()) :: binary()
  defp validate_out_dir!(out_dir) when is_binary(out_dir) do
    if String.trim(out_dir) != "" and not String.contains?(out_dir, <<0>>) do
      out_dir
    else
      Mix.raise("--out must be a non-empty filesystem path")
    end
  end

  defp validate_out_dir!(nil), do: Mix.raise("missing required option --out")
  defp validate_out_dir!(_out_dir), do: Mix.raise("--out must be a non-empty filesystem path")

  @spec validate_optional_path!(term(), atom()) :: binary() | nil
  defp validate_optional_path!(nil, _option), do: nil

  defp validate_optional_path!(path, option) when is_binary(path) do
    if String.trim(path) != "" and not String.contains?(path, <<0>>) do
      path
    else
      Mix.raise("--#{option_name(option)} must be a non-empty filesystem path")
    end
  end

  defp validate_optional_path!(_path, option) do
    Mix.raise("--#{option_name(option)} must be a non-empty filesystem path")
  end

  @spec option_name(atom()) :: binary()
  defp option_name(option), do: option |> Atom.to_string() |> String.replace("_", "-")

  @doc false
  @spec download(keyword()) :: {:ok, map()} | {:error, term()}
  def download(opts) when is_list(opts) do
    model_id = Keyword.fetch!(opts, :model)
    revision = Keyword.fetch!(opts, :revision)
    out_dir = Keyword.fetch!(opts, :out)

    with :ok <- File.mkdir_p(out_dir) do
      with_output_lock(out_dir, fn ->
        download_locked(opts, model_id, revision, out_dir)
      end)
    end
  rescue
    error -> {:error, {:download_exception, error}}
  catch
    kind, reason -> {:error, {:download_exception, {kind, reason}}}
  end

  @spec download_locked(keyword(), binary(), binary(), Path.t()) ::
          {:ok, map()} | {:error, term()}
  defp download_locked(opts, model_id, revision, out_dir) do
    with :ok <- validate_destinations(out_dir),
         {:ok, expected_checksums} <-
           load_checksum_manifest(opts, model_id, revision, out_dir),
         :ok <- validate_existing_artifacts(opts, out_dir, expected_checksums) do
      with_staging_dir(out_dir, fn staging_dir ->
        do_download(opts, staging_dir, expected_checksums)
      end)
    end
  end

  @spec with_output_lock(Path.t(), (-> {:ok, map()} | {:error, term()})) ::
          {:ok, map()} | {:error, term()}
  defp with_output_lock(out_dir, fun) do
    lock_dir = Path.join(out_dir, ".spectre-download.lock")

    case File.mkdir(lock_dir) do
      :ok ->
        try do
          fun.()
        after
          File.rmdir(lock_dir)
        end

      {:error, :eexist} ->
        {:error, {:download_locked, lock_dir}}

      {:error, reason} ->
        {:error, {:download_lock_failed, lock_dir, reason}}
    end
  end

  @spec do_download(keyword(), Path.t(), map()) :: {:ok, map()} | {:error, term()}
  defp do_download(opts, staging_dir, expected_checksums) do
    with {:ok, artifacts} <- stage_artifacts(opts, staging_dir, expected_checksums),
         {:ok, manifest, manifest_tmp} <- stage_manifest(opts, staging_dir, artifacts),
         :ok <- commit_generation(opts, staging_dir, artifacts, manifest_tmp) do
      {:ok,
       %{
         out_dir: Keyword.fetch!(opts, :out),
         manifest_path: Path.join(Keyword.fetch!(opts, :out), @manifest_name),
         manifest: manifest
       }}
    end
  end

  @spec with_staging_dir(Path.t(), (Path.t() -> {:ok, map()} | {:error, term()})) ::
          {:ok, map()} | {:error, term()}
  defp with_staging_dir(out_dir, fun) do
    staging_dir =
      Path.join(
        out_dir,
        ".spectre-download-#{random_suffix()}"
      )

    case File.mkdir(staging_dir) do
      :ok ->
        try do
          fun.(staging_dir)
        after
          File.rm_rf(staging_dir)
        end

      {:error, reason} ->
        {:error, {:staging_directory_failed, staging_dir, reason}}
    end
  end

  @spec validate_destinations(Path.t()) :: :ok | {:error, term()}
  defp validate_destinations(out_dir) do
    Enum.reduce_while(@files ++ [@manifest_name], :ok, fn file, :ok ->
      path = Path.join(out_dir, file)

      case File.lstat(path) do
        {:error, :enoent} ->
          {:cont, :ok}

        {:ok, %{type: :regular}} ->
          {:cont, :ok}

        {:ok, %{type: type}} ->
          {:halt, {:error, {:invalid_destination, path, type}}}

        {:error, reason} ->
          {:halt, {:error, {:destination_inspection_failed, path, reason}}}
      end
    end)
  end

  @spec random_suffix() :: binary()
  defp random_suffix do
    :crypto.strong_rand_bytes(12)
    |> Base.url_encode64(padding: false)
  end

  @spec validate_existing_artifacts(keyword(), Path.t(), map()) :: :ok | {:error, term()}
  defp validate_existing_artifacts(opts, out_dir, expected_checksums) do
    existing = Enum.filter(@files, &File.regular?(Path.join(out_dir, &1)))

    if existing != [] and not Keyword.get(opts, :force, false) and
         map_size(expected_checksums) == 0 do
      {:error, {:unverified_existing_artifacts, existing}}
    else
      :ok
    end
  end

  @spec stage_artifacts(keyword(), Path.t(), map()) :: {:ok, [map()]} | {:error, term()}
  defp stage_artifacts(opts, staging_dir, expected_checksums) do
    Enum.reduce_while(@files, {:ok, []}, fn file, {:ok, artifacts} ->
      case stage_artifact(file, opts, staging_dir, expected_checksums) do
        {:ok, artifact} -> {:cont, {:ok, [artifact | artifacts]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, artifacts} -> {:ok, Enum.reverse(artifacts)}
      {:error, _reason} = error -> error
    end
  end

  @spec stage_artifact(binary(), keyword(), Path.t(), map()) :: {:ok, map()} | {:error, term()}
  defp stage_artifact(file, opts, staging_dir, expected_checksums) do
    out_dir = Keyword.fetch!(opts, :out)
    destination = Path.join(out_dir, file)
    url = hf_url(Keyword.fetch!(opts, :model), Keyword.fetch!(opts, :revision), file)

    if File.regular?(destination) and not Keyword.get(opts, :force, false) do
      report(opts, "skip #{destination} (exists)")

      with :ok <- validate_artifact_file(file, destination) do
        describe_artifact(file, url, destination, nil, expected_checksums)
      end
    else
      temporary = Path.join(staging_dir, file)
      report(opts, "downloading #{url}")

      with :ok <- invoke_downloader(opts, url, temporary),
           :ok <- validate_artifact_file(file, temporary) do
        describe_artifact(file, url, temporary, destination, expected_checksums)
      end
    end
  end

  @spec describe_artifact(binary(), binary(), Path.t(), Path.t() | nil, map()) ::
          {:ok, map()} | {:error, term()}
  defp describe_artifact(file, url, source, destination, expected_checksums) do
    with {:ok, checksum} <- sha256_file(source),
         :ok <- verify_checksum(file, checksum, expected_checksums),
         {:ok, stat} <- File.stat(source) do
      {:ok,
       %{
         file: file,
         url: url,
         sha256: checksum,
         bytes: stat.size,
         source: source,
         destination: destination
       }}
    end
  end

  @spec invoke_downloader(keyword(), binary(), Path.t()) :: :ok | {:error, term()}
  defp invoke_downloader(opts, url, temporary) do
    downloader = Keyword.get(opts, :downloader, &system_download/2)

    case downloader.(url, temporary) do
      :ok -> :ok
      {:ok, _result} -> :ok
      {:error, reason} -> {:error, {:download_failed, url, reason}}
      other -> {:error, {:invalid_downloader_result, url, other}}
    end
  rescue
    error -> {:error, {:download_failed, url, error}}
  catch
    kind, reason -> {:error, {:download_failed, url, {kind, reason}}}
  end

  @spec validate_downloaded_file(Path.t()) :: :ok | {:error, term()}
  defp validate_downloaded_file(path) do
    case File.stat(path) do
      {:ok, %{type: :regular, size: size}} when size > 0 -> :ok
      {:ok, %{type: :regular}} -> {:error, {:empty_download, path}}
      {:ok, %{type: type}} -> {:error, {:invalid_download, path, type}}
      {:error, reason} -> {:error, {:missing_download, path, reason}}
    end
  end

  @spec validate_artifact_file(binary(), Path.t()) :: :ok | {:error, term()}
  defp validate_artifact_file(file, path) do
    with :ok <- validate_downloaded_file(path) do
      validate_artifact_content(file, path)
    end
  end

  @spec validate_artifact_content(binary(), Path.t()) :: :ok | {:error, term()}
  defp validate_artifact_content(file, path) when file in ["tokenizer.json", "config.json"] do
    with {:ok, payload} <- File.read(path),
         {:ok, decoded} <- Jason.decode(payload),
         true <- is_map(decoded) do
      :ok
    else
      false -> {:error, {:invalid_json_artifact, file, path, :expected_object}}
      {:error, reason} -> {:error, {:invalid_json_artifact, file, path, reason}}
    end
  end

  defp validate_artifact_content("model.onnx", path) do
    case File.open(path, [:read, :binary]) do
      {:ok, io} ->
        try do
          case IO.binread(io, 128) do
            bytes when is_binary(bytes) ->
              validate_model_prefix(bytes, path)

            :eof ->
              {:error, {:empty_download, path}}

            {:error, reason} ->
              {:error, {:model_inspection_failed, path, reason}}
          end
        after
          File.close(io)
        end

      {:error, reason} ->
        {:error, {:model_inspection_failed, path, reason}}
    end
  end

  @spec validate_model_prefix(binary(), Path.t()) :: :ok | {:error, term()}
  defp validate_model_prefix(bytes, path) do
    cond do
      String.starts_with?(bytes, @lfs_pointer_prefix) ->
        {:error, {:invalid_model_artifact, path, :git_lfs_pointer}}

      Enum.any?(@html_model_prefixes, &String.starts_with?(bytes, &1)) ->
        {:error, {:invalid_model_artifact, path, :html_response}}

      true ->
        :ok
    end
  end

  @spec stage_manifest(keyword(), Path.t(), [map()]) ::
          {:ok, map(), Path.t()} | {:error, term()}
  defp stage_manifest(opts, staging_dir, artifacts) do
    manifest = build_manifest(opts, artifacts)
    path = Path.join(staging_dir, @manifest_name)

    case Jason.encode(manifest, pretty: true) do
      {:ok, json} ->
        case File.write(path, json <> "\n", [:binary, :exclusive]) do
          :ok -> {:ok, manifest, path}
          {:error, reason} -> {:error, {:manifest_write_failed, path, reason}}
        end

      {:error, reason} ->
        {:error, {:manifest_encode_failed, reason}}
    end
  end

  @spec build_manifest(keyword(), [map()]) :: map()
  defp build_manifest(opts, artifacts) do
    files =
      Map.new(artifacts, fn artifact ->
        {artifact.file,
         %{
           "bytes" => artifact.bytes,
           "sha256" => artifact.sha256,
           "source_url" => artifact.url
         }}
      end)

    %{
      "schema_version" => 1,
      "model" => Keyword.fetch!(opts, :model),
      "revision" => Keyword.fetch!(opts, :revision),
      "files" => files
    }
  end

  @spec commit_generation(keyword(), Path.t(), [map()], Path.t()) ::
          :ok | {:error, term()}
  defp commit_generation(opts, staging_dir, artifacts, manifest_tmp) do
    artifact_entries =
      artifacts
      |> Enum.reject(&is_nil(&1.destination))
      |> Enum.map(fn artifact ->
        %{
          source: artifact.source,
          destination: artifact.destination,
          file: artifact.file
        }
      end)

    entries =
      artifact_entries ++
        [
          %{
            source: manifest_tmp,
            destination: Path.join(Keyword.fetch!(opts, :out), @manifest_name),
            file: @manifest_name
          }
        ]

    with {:ok, entries_with_backups} <- prepare_backups(entries, staging_dir) do
      install_entries(opts, entries_with_backups)
    end
  end

  @spec prepare_backups([map()], Path.t()) :: {:ok, [map()]} | {:error, term()}
  defp prepare_backups(entries, staging_dir) do
    backup_dir = Path.join(staging_dir, "backups")

    case File.mkdir(backup_dir) do
      :ok -> prepare_backup_entries(entries, backup_dir)
      {:error, reason} -> {:error, {:backup_directory_failed, backup_dir, reason}}
    end
  end

  @spec prepare_backup_entries([map()], Path.t()) :: {:ok, [map()]} | {:error, term()}
  defp prepare_backup_entries(entries, backup_dir) do
    entries
    |> Enum.with_index()
    |> Enum.reduce_while({:ok, []}, fn {entry, index}, {:ok, prepared} ->
      case prepare_backup(entry, index, backup_dir) do
        {:ok, prepared_entry} -> {:cont, {:ok, [prepared_entry | prepared]}}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
    |> case do
      {:ok, prepared} -> {:ok, Enum.reverse(prepared)}
      {:error, _reason} = error -> error
    end
  end

  @spec prepare_backup(map(), non_neg_integer(), Path.t()) :: {:ok, map()} | {:error, term()}
  defp prepare_backup(entry, index, backup_dir) do
    case File.lstat(entry.destination) do
      {:error, :enoent} ->
        {:ok, Map.put(entry, :backup, nil)}

      {:ok, %{type: :regular}} ->
        backup = Path.join(backup_dir, "#{index}-#{entry.file}")

        case backup_file(entry.destination, backup) do
          :ok -> {:ok, Map.put(entry, :backup, backup)}
          {:error, reason} -> {:error, {:backup_failed, entry.destination, reason}}
        end

      {:ok, %{type: type}} ->
        {:error, {:invalid_destination, entry.destination, type}}

      {:error, reason} ->
        {:error, {:destination_inspection_failed, entry.destination, reason}}
    end
  end

  @spec backup_file(Path.t(), Path.t()) :: :ok | {:error, term()}
  defp backup_file(source, backup) do
    case File.ln(source, backup) do
      :ok ->
        :ok

      {:error, link_reason} ->
        case File.cp(source, backup) do
          :ok -> :ok
          {:error, copy_reason} -> {:error, {:link, link_reason, :copy, copy_reason}}
        end
    end
  end

  @spec install_entries(keyword(), [map()]) :: :ok | {:error, term()}
  defp install_entries(opts, entries) do
    case install_entry_set(opts, entries) do
      {:ok, _installed} ->
        :ok

      {:error, install_error, installed} ->
        recover_failed_install(install_error, installed)
    end
  end

  @spec install_entry_set(keyword(), [map()]) ::
          {:ok, [map()]} | {:error, term(), [map()]}
  defp install_entry_set(opts, entries) do
    Enum.reduce_while(entries, {:ok, []}, fn entry, {:ok, installed} ->
      case invoke_renamer(opts, entry.source, entry.destination) do
        :ok -> {:cont, {:ok, [entry | installed]}}
        {:error, reason} -> {:halt, {:error, reason, installed}}
      end
    end)
  end

  @spec recover_failed_install(term(), [map()]) :: {:error, term()}
  defp recover_failed_install(install_error, installed) do
    case rollback_entries(installed) do
      :ok ->
        {:error, install_error}

      {:error, rollback_errors} ->
        {:error, {:install_failed_with_rollback_errors, install_error, rollback_errors}}
    end
  end

  @spec invoke_renamer(keyword(), Path.t(), Path.t()) :: :ok | {:error, term()}
  defp invoke_renamer(opts, source, destination) do
    renamer = Keyword.get(opts, :renamer, &File.rename/2)

    case renamer.(source, destination) do
      :ok -> :ok
      {:error, reason} -> {:error, {:atomic_rename_failed, destination, reason}}
      other -> {:error, {:invalid_renamer_result, destination, other}}
    end
  rescue
    error -> {:error, {:atomic_rename_failed, destination, error}}
  catch
    kind, reason -> {:error, {:atomic_rename_failed, destination, {kind, reason}}}
  end

  @spec rollback_entries([map()]) :: :ok | {:error, [term()]}
  defp rollback_entries(installed) do
    errors =
      Enum.reduce(installed, [], fn entry, errors ->
        case rollback_entry(entry) do
          :ok -> errors
          {:error, reason} -> [reason | errors]
        end
      end)

    case errors do
      [] -> :ok
      errors -> {:error, Enum.reverse(errors)}
    end
  end

  @spec rollback_entry(map()) :: :ok | {:error, term()}
  defp rollback_entry(%{backup: nil, destination: destination}) do
    case File.rm(destination) do
      :ok -> :ok
      {:error, :enoent} -> :ok
      {:error, reason} -> {:error, {:rollback_remove_failed, destination, reason}}
    end
  end

  defp rollback_entry(%{backup: backup, destination: destination}) do
    case File.rename(backup, destination) do
      :ok -> :ok
      {:error, reason} -> {:error, {:rollback_restore_failed, destination, reason}}
    end
  end

  @spec load_checksum_manifest(keyword(), binary(), binary(), Path.t()) ::
          {:ok, map()} | {:error, term()}
  defp load_checksum_manifest(opts, model_id, revision, out_dir) do
    case checksum_manifest_path(opts, out_dir) do
      nil ->
        {:ok, %{}}

      path ->
        with {:ok, bytes} <- File.read(path),
             {:ok, manifest} <- Jason.decode(bytes),
             :ok <- validate_manifest_identity(manifest, model_id, revision),
             {:ok, checksums} <- manifest_checksums(manifest) do
          {:ok, checksums}
        else
          {:error, reason} -> {:error, {:checksum_manifest_invalid, path, reason}}
        end
    end
  end

  @spec checksum_manifest_path(keyword(), Path.t()) :: Path.t() | nil
  defp checksum_manifest_path(opts, out_dir) do
    explicit = Keyword.get(opts, :checksum_manifest)
    generated = Path.join(out_dir, @manifest_name)

    cond do
      explicit ->
        explicit

      not Keyword.get(opts, :force, false) and File.regular?(generated) ->
        generated

      true ->
        nil
    end
  end

  @spec validate_manifest_identity(term(), binary(), binary()) :: :ok | {:error, term()}
  defp validate_manifest_identity(
         %{"schema_version" => 1, "model" => model_id, "revision" => revision},
         model_id,
         revision
       ),
       do: :ok

  defp validate_manifest_identity(%{"schema_version" => version}, _model_id, _revision)
       when version != 1,
       do: {:error, {:unsupported_schema_version, version}}

  defp validate_manifest_identity(%{"model" => actual}, model_id, _revision)
       when actual != model_id,
       do: {:error, {:model_mismatch, model_id, actual}}

  defp validate_manifest_identity(%{"revision" => actual}, _model_id, revision)
       when actual != revision,
       do: {:error, {:revision_mismatch, revision, actual}}

  defp validate_manifest_identity(_manifest, _model_id, _revision),
    do: {:error, :missing_manifest_identity}

  @spec manifest_checksums(map()) :: {:ok, map()} | {:error, term()}
  defp manifest_checksums(%{"files" => files}) when is_map(files) do
    Enum.reduce_while(@files, {:ok, %{}}, fn file, {:ok, checksums} ->
      with {:ok, entry} <- Map.fetch(files, file),
           {:ok, checksum} <- manifest_checksum(entry),
           true <- Regex.match?(@sha256_pattern, checksum) do
        {:cont, {:ok, Map.put(checksums, file, String.downcase(checksum))}}
      else
        :error -> {:halt, {:error, {:missing_checksum, file}}}
        false -> {:halt, {:error, {:invalid_checksum, file}}}
        {:error, reason} -> {:halt, {:error, {reason, file}}}
      end
    end)
  end

  defp manifest_checksums(_manifest), do: {:error, :missing_manifest_files}

  @spec manifest_checksum(term()) :: {:ok, binary()} | {:error, atom()}
  defp manifest_checksum(checksum) when is_binary(checksum), do: {:ok, checksum}

  defp manifest_checksum(%{"sha256" => checksum}) when is_binary(checksum),
    do: {:ok, checksum}

  defp manifest_checksum(_entry), do: {:error, :invalid_checksum_entry}

  @spec verify_checksum(binary(), binary(), map()) :: :ok | {:error, term()}
  defp verify_checksum(file, actual, expected_checksums) do
    case Map.fetch(expected_checksums, file) do
      :error ->
        :ok

      {:ok, ^actual} ->
        :ok

      {:ok, expected} ->
        {:error, {:checksum_mismatch, file, expected, actual}}
    end
  end

  @spec sha256_file(Path.t()) :: {:ok, binary()} | {:error, term()}
  defp sha256_file(path) do
    path
    |> File.stream!(1_048_576, [])
    |> Enum.reduce(:crypto.hash_init(:sha256), &:crypto.hash_update(&2, &1))
    |> :crypto.hash_final()
    |> Base.encode16(case: :lower)
    |> then(&{:ok, &1})
  rescue
    error -> {:error, {:checksum_failed, path, error}}
  end

  @spec system_download(binary(), Path.t()) :: :ok | {:error, term()}
  defp system_download(url, destination) do
    cond do
      curl = System.find_executable("curl") ->
        {output, status} =
          System.cmd(
            curl,
            [
              "-fsSL",
              "--retry",
              "3",
              "--proto",
              "=https",
              "--proto-redir",
              "=https",
              url,
              "-o",
              destination
            ],
            stderr_to_stdout: true
          )

        if status == 0, do: :ok, else: {:error, {:curl, status, output}}

      wget = System.find_executable("wget") ->
        {output, status} =
          System.cmd(wget, ["-q", "--https-only", "-O", destination, url],
            stderr_to_stdout: true
          )

        if status == 0, do: :ok, else: {:error, {:wget, status, output}}

      true ->
        {:error, :curl_or_wget_required}
    end
  end

  @spec report(keyword(), binary()) :: :ok
  defp report(opts, message) do
    case Keyword.get(opts, :reporter) do
      reporter when is_function(reporter, 1) ->
        reporter.(message)
        :ok

      _other ->
        :ok
    end
  end

  @spec format_error(term()) :: binary()
  defp format_error(reason), do: "encoder download failed: #{inspect(reason)}"
end
